#dataSource
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/v12?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
    username: root
    password: root

dubbo:
  application:
    name: dubbo-springboot-provider
  registry:
    protocol: zookeeper
    address: 192:168:220:128:2181
  protocol:
    port: 20880